### ISSUE TITLE
[FEAT] 홈 기능구현

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/AOS_inIT#23]
## 🌻 Issue
홈 기능을 구현합니다.

## 📑 To-do
- [x] 소속 프로젝트 vp 연결
- [x] 추천 프로젝트 rv 연결
- [x] 전체보기 > 추천프로젝트 rv연결
