### ISSUE TITLE
[FEAT] 피드 글쓰기 로직 완성

### ISSUE THREAD

**Issue by stopkite** [Team-InIT/AOS_inIT#59]
## 🌻 Issue
피드 글쓰기 로직을 완성합니다.

## 📑 To-do
- [x] 바텀시트 추가 (프로젝트/기술스택)
- [x] 글쓰기 버튼 클릭 후 화면이동
- [x] 글쓰기 버튼 클릭 후 데이터 추가
